### PR TITLE
Override the upstream

### PR DESCRIPTION
**Pull request by pdhara**
Force local override of upstream
https://github.com/m-mizutani/gofalcon/pull/4/files

### CODE REVIEW

**Comment by pdhara** [comment]
Closing this

**Comment by m-mizutani** [comment]
I'm not sure clearly what do you want to claim by this PR, but make sense changing endpoint to overridable. If so, let me update to add CLI argument to specify API endpoint.

**Comment by pdhara** [comment]
Thank you for the reply, some crowdstrike customers have different endpoints. Your project is really valuable, however due to the hardcoded URL, it didn't work for me without forking your repo and changing it. 

A CLI argument to specify API endpoint will be great.

I closed the PR as I didn't know how to properly parameterize this.

**Comment by m-mizutani** [comment]
@pdhara  I published [v0.2.0](https://github.com/m-mizutani/falconstream/releases/tag/v0.2.0) including `--endpoint` option. It make falconstream able to use API endpoint other than `https://api.crowdstrike.com`. Please let me know if something wrong. (I can not verify the option because our endpoint is `https://api.crowdstrike.com` )

**Pull request closed without merging**
